// Generates the launch-content SQL files from the data/ modules:
//   supabase/content/launch-claims.sql    Claims Examined reviews (drafts)
//   supabase/content/launch-articles.sql  articles and dispatches (drafts)
//   supabase/content/cover-photos.sql     cover photos for posts that already exist
// Run: node scripts/generate-content.mjs
// Every file is safe to re-run: sources are inserted once, posts are upserted
// by (type, slug) and their source links are replaced.
import { writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import * as claimData from '../data/launch-claims.js';
import * as articleData from '../data/launch-articles.js';
import { photos, existingCovers } from '../data/photos.js';

const uuid = (key) => {
  const h = createHash('md5').update(key).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
};
const sid = (key) => uuid(`launch-source:${key}`);
const q = (v) => (v === null || v === undefined || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => (v === null || v === undefined ? 'null' : `${q(JSON.stringify(v))}::jsonb`);
const hero = (key) => {
  if (!key) return null;
  if (!photos[key]) throw new Error(`Unknown photo: ${key}`);
  return photos[key];
};

function build({ posts, sources, header }) {
  const used = new Set(posts.flatMap((p) => [...p.sources, ...p.footnotes.map((f) => f.source).filter(Boolean)]));
  for (const key of used) if (!sources[key]) throw new Error(`Unknown source key: ${key}`);

  const out = [...header, '', 'begin;', '', '-- Sources'];
  for (const key of used) {
    const s = sources[key];
    out.push(
      `insert into public.sources (id, kind, author, title, publication, year, pages, url) values (${q(sid(key))}, ${q(s.kind)}, ${q(s.author)}, ${q(s.title)}, ${q(s.publication)}, ${s.year ?? 'null'}, ${q(s.pages)}, ${q(s.url)}) on conflict (id) do nothing;`
    );
  }

  for (const p of posts) {
    const footnotes = p.footnotes.map((f, i) => ({ n: i + 1, text: f.text, source_id: f.source ? sid(f.source) : null }));
    const sel = `(select id from public.posts where type = ${q(p.type)} and slug = ${q(p.slug)})`;
    out.push(
      '',
      `-- ${p.title}`,
      `insert into public.posts (type, slug, title, dek, topic_id, author_id, status, featured, reading_minutes, hero, body, footnotes, corrections, claim, dispatch, related_slug) values (` +
        [
          q(p.type),
          q(p.slug),
          q(p.title),
          q(p.dek),
          `(select id from public.topics where slug = ${q(p.topic)})`,
          `(select id from public.authors where slug = 'editor')`,
          `'draft'`,
          p.featured ? 'true' : 'false',
          p.reading_minutes ?? 'null',
          j(hero(p.photo)),
          j(p.body),
          j(footnotes),
          `'[]'::jsonb`,
          j(p.claim ?? null),
          j(p.dispatch ?? null),
          q(p.related_slug),
        ].join(', ') +
        `)`,
      `  on conflict (type, slug) do update set title = excluded.title, dek = excluded.dek, topic_id = excluded.topic_id, author_id = excluded.author_id, status = 'draft', reading_minutes = excluded.reading_minutes, hero = excluded.hero, body = excluded.body, footnotes = excluded.footnotes, claim = excluded.claim, dispatch = excluded.dispatch, related_slug = excluded.related_slug;`,
      `delete from public.post_sources where post_id = ${sel};`
    );
    p.sources.forEach((key, i) => {
      out.push(`insert into public.post_sources (post_id, source_id, sort) values (${sel}, ${q(sid(key))}, ${i});`);
    });
  }
  out.push('', 'commit;', '');
  return out.join('\n');
}

const dir = new URL('../supabase/content/', import.meta.url);
mkdirSync(dir, { recursive: true });

const claims = claimData.claims.map((c) => ({ ...c, type: 'claim' }));
writeFileSync(
  new URL('launch-claims.sql', dir),
  build({
    posts: claims,
    sources: claimData.sources,
    header: [
      '-- Launch Claims Examined reviews (generated by scripts/generate-content.mjs).',
      '-- Run in Supabase → SQL Editor AFTER the migrations. Posts arrive as DRAFTS:',
      '-- review each in /studio and press Publish. Re-running resets them to draft.',
    ],
  })
);

writeFileSync(
  new URL('launch-articles.sql', dir),
  build({
    posts: articleData.posts,
    sources: articleData.sources,
    header: [
      '-- Launch articles and dispatches (generated by scripts/generate-content.mjs).',
      '-- Run in Supabase → SQL Editor AFTER the migrations. Posts arrive as DRAFTS:',
      '-- review each in /studio and press Publish. Re-running resets them to draft.',
    ],
  })
);

const covers = [
  '-- Cover photos for posts that already exist (generated by scripts/generate-content.mjs).',
  '-- Only touches posts that are present; safe to re-run.',
  '',
  ...existingCovers.map(
    (c) => `update public.posts set hero = ${j(hero(c.photo))} where type = ${q(c.type)} and slug = ${q(c.slug)};`
  ),
  '',
];
writeFileSync(new URL('cover-photos.sql', dir), covers.join('\n'));

console.log(`claims: ${claims.length}, articles+dispatches: ${articleData.posts.length}, covers: ${existingCovers.length}`);
