// Generates supabase/seed.sql from data/dummy.js so the database starts with
// the same sample content as the stage 1 site.
//   node scripts/generate-seed.mjs
import { writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { topics, authors, sources, posts } from '../data/dummy.js';

// Deterministic UUIDs: the same as Postgres md5(key)::uuid, so re-running is idempotent.
const uuid = (key) => {
  const h = createHash('md5').update(key).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
};
const sid = (id) => uuid(`source:${id}`);
const pid = (id) => uuid(`post:${id}`);

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => (v === null || v === undefined ? 'null' : `${q(JSON.stringify(v))}::jsonb`);
const topicSlug = (id) => topics.find((t) => t.id === id)?.slug;
const authorSlug = (id) => authors.find((a) => a.id === id)?.slug;

const lines = [
  '-- Sample content (generated by scripts/generate-seed.mjs). Run AFTER 0001_init.sql.',
  '-- Safe to re-run. Delete these rows from the studio once real content exists.',
  '',
];

for (const s of sources) {
  lines.push(
    `insert into public.sources (id, kind, author, title, publication, year, pages, url) values (${q(sid(s.id))}, ${q(s.kind)}, ${q(s.author)}, ${q(s.title)}, ${q(s.publication)}, ${s.year ?? 'null'}, ${q(s.pages)}, ${q(s.url)}) on conflict (id) do nothing;`
  );
}
lines.push('');

for (const p of posts) {
  const footnotes = (p.footnotes ?? []).map((f) => ({ ...f, source_id: f.source_id ? sid(f.source_id) : null }));
  lines.push(
    `insert into public.posts (id, type, slug, title, dek, topic_id, author_id, status, featured, published_at, reading_minutes, hero, body, footnotes, corrections, video, claim, dispatch, related_slug) values (` +
      [
        q(pid(p.id)),
        q(p.type),
        q(p.slug),
        q(p.title),
        q(p.dek),
        `(select id from public.topics where slug = ${q(topicSlug(p.topic_id))})`,
        `(select id from public.authors where slug = ${q(authorSlug(p.author_id))})`,
        q(p.status),
        p.featured ? 'true' : 'false',
        q(p.published_at),
        p.reading_minutes ?? 'null',
        j(p.hero),
        j(p.body ?? []),
        j(footnotes),
        j(p.corrections ?? []),
        j(p.video),
        j(p.claim),
        j(p.dispatch),
        q(p.related_slug),
      ].join(', ') +
      `) on conflict (id) do nothing;`
  );
  (p.source_ids ?? []).forEach((s, i) => {
    lines.push(
      `insert into public.post_sources (post_id, source_id, sort) values (${q(pid(p.id))}, ${q(sid(s))}, ${i}) on conflict do nothing;`
    );
  });
}

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), lines.join('\n') + '\n');
console.log(`seed.sql: ${sources.length} sources, ${posts.length} posts`);
