// Generates supabase/content/launch-claims.sql from data/launch-claims.js.
//   node scripts/generate-content.mjs
// The SQL is safe to re-run: sources are inserted once, posts are upserted by
// (type, slug), and each post's source links are replaced.
import { writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { claims, sources } from '../data/launch-claims.js';

const uuid = (key) => {
  const h = createHash('md5').update(key).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
};
const sid = (key) => uuid(`launch-source:${key}`);
const q = (v) => (v === null || v === undefined || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => (v === null || v === undefined ? 'null' : `${q(JSON.stringify(v))}::jsonb`);

const used = new Set(claims.flatMap((c) => [...c.sources, ...c.footnotes.map((f) => f.source).filter(Boolean)]));
for (const key of used) if (!sources[key]) throw new Error(`Unknown source key: ${key}`);

const out = [
  '-- Launch Claims Examined reviews (generated by scripts/generate-content.mjs).',
  '-- Run in Supabase → SQL Editor AFTER 0001_init.sql and 0002_grants.sql.',
  '-- Posts arrive as DRAFTS: review each in /studio and press Publish.',
  '',
  'begin;',
  '',
  '-- Sources',
];

for (const key of used) {
  const s = sources[key];
  out.push(
    `insert into public.sources (id, kind, author, title, publication, year, pages, url) values (${q(sid(key))}, ${q(s.kind)}, ${q(s.author)}, ${q(s.title)}, ${q(s.publication)}, ${s.year ?? 'null'}, ${q(s.pages)}, ${q(s.url)}) on conflict (id) do nothing;`
  );
}

for (const c of claims) {
  const footnotes = c.footnotes.map((f, i) => ({ n: i + 1, text: f.text, source_id: f.source ? sid(f.source) : null }));
  const sel = `(select id from public.posts where type = 'claim' and slug = ${q(c.slug)})`;
  out.push(
    '',
    `-- ${c.title}`,
    `insert into public.posts (type, slug, title, dek, topic_id, author_id, status, body, footnotes, corrections, claim, related_slug) values ('claim', ${q(c.slug)}, ${q(c.title)}, ${q(c.dek)}, (select id from public.topics where slug = ${q(c.topic)}), (select id from public.authors where slug = 'editor'), 'draft', ${j(c.body)}, ${j(footnotes)}, '[]'::jsonb, ${j(c.claim)}, ${q(c.related_slug)})`,
    `  on conflict (type, slug) do update set title = excluded.title, dek = excluded.dek, topic_id = excluded.topic_id, author_id = excluded.author_id, status = 'draft', body = excluded.body, footnotes = excluded.footnotes, claim = excluded.claim, related_slug = excluded.related_slug;`,
    `delete from public.post_sources where post_id = ${sel};`
  );
  c.sources.forEach((key, i) => {
    out.push(`insert into public.post_sources (post_id, source_id, sort) values (${sel}, ${q(sid(key))}, ${i});`);
  });
}

out.push('', 'commit;', '');
mkdirSync(new URL('../supabase/content/', import.meta.url), { recursive: true });
writeFileSync(new URL('../supabase/content/launch-claims.sql', import.meta.url), out.join('\n'));
console.log(`launch-claims.sql: ${claims.length} claims, ${used.size} sources`);
